export const INIT = '@@INIT';

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED';
export const CONNECTION_UPDATED = 'CONNECTION_UPDATED';

export const START_LOADING_WALLET = 'START_LOADING_WALLET';
export const WALLET_LOADED = 'WALLET_LOADED';

export const UPDATE_TOKENS = 'UPDATE_TOKENS';
export const TOKENS_LOADED = 'TOKENS_LOADED';

export const WEB3_WAITING = 'WEB3_WAITING';

export const SHOW_CONNECTOR_MODAL = 'SHOW_CONNECTOR_MODAL';
export const SHOW_CONFIRMATION_MODAL = 'SHOW_CONFIRMATION_MODAL';
export const UPDATE_APPROVED_TOKENS = 'UPDATE_APPROVED_TOKENS';

export const UPDATE_MODAL_STATE = 'UPDATE_MODAL_STATE';

export const FETCH_WALLET = 'FETCH_WALLET';
